version: '3.4'

services:
  pdf:
    image: pdf
    build:
      context: .
      dockerfile: src/Pdf/Dockerfile
    ports:
      - 5000
    environment:
      - HtmlWatcher__HtmlWatcherPath=/html
      - DOTNET_USE_POLLING_FILE_WATCHER=1
    volumes:
      - ./html:/html