FROM mcr.microsoft.com/dotnet/sdk:5.0-alpine AS base
WORKDIR /app
EXPOSE 5000
ENV ASPNETCORE_URLS="http://*:5000"
ENV PUPPETEER_EXECUTABLE_PATH "/usr/bin/chromium-browser"

# Puppeteer
RUN apk update && apk upgrade && \
    echo @edge http://nl.alpinelinux.org/alpine/edge/community >> /etc/apk/repositories && \
    echo @edge http://nl.alpinelinux.org/alpine/edge/main >> /etc/apk/repositories && \
    apk add --no-cache \
      chromium \
      harfbuzz \
      nss \
      fontconfig \
      wkhtmltopdf

RUN ln -s /usr/lib/libwkhtmltox.so.0 /usr/lib/libwkhtmltox.so

# Install fonts
RUN mkdir -p /usr/share/fonts/opentype
COPY ./fonts/*.otf /usr/share/fonts/opentype/
RUN fc-cache -f -v

FROM base AS build
WORKDIR /app
ENTRYPOINT [ "dotnet", "watch", "--project", "./src/Pdf", "run", "--urls", "http://0.0.0.0:5000" ]